#page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: # 1234793120 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: https://apps.apple.com/ca/app/montr%C3%A9al-47/id1536069398 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
# playstore_link: # Enter Google Play Store URL.
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: /assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Montréal 47 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: 2,79 $ CAD # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Photos aériennes de Montréal en 1947

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Étienne Léonard-Dufour
your_link: https://websurmesure.com
your_city:
email_address:
facebook_username:
instagram_username:
twitter_usernamePar:
github_username:
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
    - title: Carte de 1924
      description: Découvrez une carte de Montréal de 1924 numérisée en haute définition.
      fontawesome_icon_name: mobile
    - title: Images aériennes de 1947
      description: Observez les images aériennes prises par la ville de Montréal entre 1947 et 1949.
      fontawesome_icon_name: mobile
    - title: Images aérienne de 2020
      description: Comparez les cartes avec un fond aérien de 2020.
      fontawesome_icon_name: mobile

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: /assets/headerimage.jpg # Replace with alternative image path or image URL.
cover_overlay_color: "rgb(50, 50, 50)"
cover_overlay_transparency: 0.4

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
    style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
    - LICENSE
    - README.md
    - CNAME

collections:
    pages:
        output: true
        permalink: /:path/

# Markdown rendering
markdown: kramdown
